var books = [
  {
    "author": "Chinua Achebe",
    "country": "Nigeria",
    "imageLink": "img/books/things-fall-apart.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Things_Fall_Apart",
    "pages": 209,
    "imdbId": "tt7026230",
    "title": "Things Fall Apart",
    "year": 1958
  },
  {
    "author": "Hans Christian Andersen",
    "country": "Denmark",
    "imageLink": "img/books/fairy-tales.jpg",
    "language": "Danish",
    "link": "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.",
    "pages": 784,
    "imdbId": "tt0436629",
    "title": "Fairy tales",
    "year": 1836
  },
  {
    "author": "Dante Alighieri",
    "country": "Italy",
    "imageLink": "img/books/the-divine-comedy.jpg",
    "language": "Italian",
    "link": "https://en.wikipedia.org/wiki/Divine_Comedy",
    "pages": 928,
    "imdbId": "tt0300195",
    "title": "The Divine Comedy",
    "year": 1315
  },
  {
    "author": "Unknown",
    "country": "Sumer and Akkadian Empire",
    "imageLink": "img/books/the-epic-of-gilgamesh.jpg",
    "language": "Akkadian",
    "link": "https://en.wikipedia.org/wiki/Epic_of_Gilgamesh",
    "pages": 160,
    "imdbId": "tt0329374",
    "title": "The Epic Of Gilgamesh",
    "year": 1700
  },
  {
    "author": "Unknown",
    "country": "Achaemenid Empire",
    "imageLink": "img/books/the-book-of-job.jpg",
    "language": "Hebrew",
    "link": "https://en.wikipedia.org/wiki/Book_of_Job",
    "pages": 176,
    "imdbId": "tt2018111",
    "title": "The Book Of Job",
    "year": 600
  },
  {
    "author": "Unknown",
    "country": "India/Iran/Iraq/Egypt/Tajikistan",
    "imageLink": "img/books/one-thousand-and-one-nights.jpg",
    "language": "Arabic",
    "link": "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights",
    "pages": 288,
    "imdbId": "tt0208185",
    "title": "One Thousand and One Nights",
    "year": 1200
  },
  {
    "author": "Unknown",
    "country": "Iceland",
    "imageLink": "img/books/njals-saga.jpg",
    "language": "Old Norse",
    "link": "https://en.wikipedia.org/wiki/Nj%C3%A1ls_saga",
    "pages": 384,
    "imdbId": "tt5117670",
    "title": "Nj\u00e1l's Saga",
    "year": 1350
  },
  {
    "author": "Jane Austen",
    "country": "United Kingdom",
    "imageLink": "img/books/pride-and-prejudice.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Pride_and_Prejudice",
    "pages": 226,
    "imdbId": "tt0996605",
    "title": "Pride and Prejudice",
    "year": 1813
  },
  {
    "author": "Honor\u00e9 de Balzac",
    "country": "France",
    "imageLink": "img/books/le-pere-goriot.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot",
    "pages": 443,
    "imdbId": "tt7614404",
    "title": "Le P\u00e8re Goriot",
    "year": 1835
  },
  {
    "author": "Samuel Beckett",
    "country": "Republic of Ireland",
    "imageLink": "img/books/molloy-malone-dies-the-unnamable.jpg",
    "language": "French, English",
    "link": "https://en.wikipedia.org/wiki/Molloy_(novel)",
    "pages": 256,
    "imdbId": "tt2057931",
    "title": "Molloy, Malone Dies, The Unnamable, the trilogy",
    "year": 1952
  },
  {
    "author": "Giovanni Boccaccio",
    "country": "Italy",
    "imageLink": "img/books/bola.jpg",
    "language": "Italian",
    "link": "https://en.wikipedia.org/wiki/The_Decameron",
    "pages": 1024,
    "imdbId": "tt4103724",
    "title": "The Decameron",
    "year": 1351
  },
  {
    "author": "Jorge Luis Borges",
    "country": "Argentina",
    "imageLink": "img/books/ficciones.jpg",
    "language": "Spanish",
    "link": "https://en.wikipedia.org/wiki/Ficciones",
    "pages": 224,
    "imdbId": "tt7379330",
    "title": "Ficciones",
    "year": 1965
  },
  {
    "author": "Emily Bront\u00eb",
    "country": "United Kingdom",
    "imageLink": "img/books/wuthering-heights.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Wuthering_Heights",
    "pages": 342,
    "imdbId": "tt5818010",
    "title": "Wuthering Heights",
    "year": 1847
  },
  {
    "author": "Albert Camus",
    "country": "Algeria, French Empire",
    "imageLink": "img/books/l-etranger.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/The_Stranger_(novel)",
    "pages": 185,
    "imdbId": "tt2522908",
    "title": "The Stranger",
    "year": 1942
  },
  {
    "author": "Paul Celan",
    "country": "Romania, France",
    "imageLink": "img/books/poems-paul-celan.jpg",
    "language": "German",
    "link": "",
    "pages": 320,
    "imdbId": "tt7133554",
    "title": "Poems",
    "year": 1952
  },
  {
    "author": "Louis-Ferdinand C\u00e9line",
    "country": "France",
    "imageLink": "img/books/voyage-au-bout-de-la-nuit.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/Journey_to_the_End_of_the_Night",
    "pages": 505,
    "imdbId": "tt7167602",
    "title": "Journey to the End of the Night",
    "year": 1932
  },
  {
    "author": "Miguel de Cervantes",
    "country": "Spain",
    "imageLink": "img/books/don-quijote-de-la-mancha.jpg",
    "language": "Spanish",
    "link": "https://en.wikipedia.org/wiki/Don_Quixote",
    "pages": 1056,
    "imdbId": "tt5085924",
    "title": "Don Quijote De La Mancha",
    "year": 1610
  },
  {
    "author": "Geoffrey Chaucer",
    "country": "England",
    "imageLink": "img/books/the-canterbury-tales.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/The_Canterbury_Tales",
    "pages": 544,
    "imdbId": "tt6143568",
    "title": "The Canterbury Tales",
    "year": 1450
  },
  {
    "author": "Anton Chekhov",
    "country": "Russia",
    "imageLink": "img/books/stories-of-anton-chekhov.jpg",
    "language": "Russian",
    "link": "https://en.wikipedia.org/wiki/List_of_short_stories_by_Anton_Chekhov",
    "pages": 194,
    "imdbId": "tt2349677",
    "title": "Stories",
    "year": 1886
  },
  {
    "author": "Joseph Conrad",
    "country": "United Kingdom",
    "imageLink": "img/books/nostromo.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Nostromo",
    "pages": 320,
    "imdbId": "tt5030452",
    "title": "Nostromo",
    "year": 1904
  },
  {
    "author": "Charles Dickens",
    "country": "United Kingdom",
    "imageLink": "img/books/great-expectations.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Great_Expectations",
    "pages": 194,
    "imdbId": "tt6900092",
    "title": "Great Expectations",
    "year": 1861
  },
  {
    "author": "Denis Diderot",
    "country": "France",
    "imageLink": "img/books/jacques-the-fatalist.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/Jacques_the_Fatalist",
    "pages": 596,
    "imdbId": "tt6543420",
    "title": "Jacques the Fatalist",
    "year": 1796
  },
  {
    "author": "Alfred D\u00f6blin",
    "country": "Germany",
    "imageLink": "img/books/berlin-alexanderplatz.jpg",
    "language": "German",
    "link": "https://en.wikipedia.org/wiki/Berlin_Alexanderplatz",
    "pages": 600,
    "imdbId": "tt5903088",
    "title": "Berlin Alexanderplatz",
    "year": 1929
  },
  {
    "author": "Fyodor Dostoevsky",
    "country": "Russia",
    "imageLink": "img/books/crime-and-punishment.jpg",
    "language": "Russian",
    "link": "https://en.wikipedia.org/wiki/Crime_and_Punishment",
    "pages": 551,
    "imdbId": "tt7630164",
    "title": "Crime and Punishment",
    "year": 1866
  },
  {
    "author": "Fyodor Dostoevsky",
    "country": "Russia",
    "imageLink": "img/books/the-idiot.jpg",
    "language": "Russian",
    "link": "https://en.wikipedia.org/wiki/The_Idiot",
    "pages": 656,
    "imdbId": "tt4456850",
    "title": "The Idiot",
    "year": 1869
  },
  {
    "author": "Fyodor Dostoevsky",
    "country": "Russia",
    "imageLink": "img/books/the-possessed.jpg",
    "language": "Russian",
    "link": "https://en.wikipedia.org/wiki/Demons_(Dostoyevsky_novel)",
    "pages": 768,
    "imdbId": "tt1537196",
    "title": "The Possessed",
    "year": 1872
  },
  {
    "author": "Fyodor Dostoevsky",
    "country": "Russia",
    "imageLink": "img/books/the-brothers-karamazov.jpg",
    "language": "Russian",
    "link": "https://en.wikipedia.org/wiki/The_Brothers_Karamazov",
    "pages": 824,
    "imdbId": "tt5478478",
    "title": "The Brothers Karamazov",
    "year": 1880
  },
  {
    "author": "George Eliot",
    "country": "United Kingdom",
    "imageLink": "img/books/middlemarch.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Middlemarch",
    "pages": 800,
    "imdbId": "tt4500922",
    "title": "Middlemarch",
    "year": 1871
  },
  {
    "author": "Ralph Ellison",
    "country": "United States",
    "imageLink": "img/books/invisible-man.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Invisible_Man",
    "pages": 581,
    "imdbId": "tt1259528",
    "title": "Invisible Man",
    "year": 1952
  },
  {
    "author": "Euripides",
    "country": "Greece",
    "imageLink": "img/books/medea.jpg",
    "language": "Greek",
    "link": "https://en.wikipedia.org/wiki/Medea_(play)",
    "pages": 104,
    "imdbId": "tt6413410",
    "title": "Medea",
    "year": 431
  },
  {
    "author": "William Faulkner",
    "country": "United States",
    "imageLink": "img/books/absalom-absalom.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Absalom,_Absalom!",
    "pages": 313,
    "imdbId": "tt0841046",
    "title": "Absalom, Absalom!",
    "year": 1936
  },
  {
    "author": "William Faulkner",
    "country": "United States",
    "imageLink": "img/books/the-sound-and-the-fury.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/The_Sound_and_the_Fury",
    "pages": 326,
    "imdbId": "tt0322330",
    "title": "The Sound and the Fury",
    "year": 1929
  },
  {
    "author": "Gustave Flaubert",
    "country": "France",
    "imageLink": "img/books/madame-bovary.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/Madame_Bovary",
    "pages": 528,
    "imdbId": "tt6101820",
    "title": "Madame Bovary",
    "year": 1857
  },
  {
    "author": "Gustave Flaubert",
    "country": "France",
    "imageLink": "img/books/l-education-sentimentale.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/Sentimental_Education",
    "pages": 606,
    "imdbId": "tt2388986",
    "title": "Sentimental Education",
    "year": 1869
  },
  {
    "author": "Federico Garc\u00eda Lorca",
    "country": "Spain",
    "imageLink": "img/books/gypsy-ballads.jpg",
    "language": "Spanish",
    "link": "https://en.wikipedia.org/wiki/Gypsy_Ballads",
    "pages": 218,
    "imdbId": "tt2636806",
    "title": "Gypsy Ballads",
    "year": 1928
  },
  {
    "author": "Gabriel Garc\u00eda M\u00e1rquez",
    "country": "Colombia",
    "imageLink": "img/books/one-hundred-years-of-solitude.jpg",
    "language": "Spanish",
    "link": "https://en.wikipedia.org/wiki/One_Hundred_Years_of_Solitude",
    "pages": 417,
    "imdbId": "tt0983213",
    "title": "One Hundred Years of Solitude",
    "year": 1967
  },
  {
    "author": "Gabriel Garc\u00eda M\u00e1rquez",
    "country": "Colombia",
    "imageLink": "img/books/love-in-the-time-of-cholera.jpg",
    "language": "Spanish",
    "link": "https://en.wikipedia.org/wiki/Love_in_the_Time_of_Cholera",
    "pages": 368,
    "imdbId": "tt5598102",
    "title": "Love in the Time of Cholera",
    "year": 1985
  },
  {
    "author": "Johann Wolfgang von Goethe",
    "country": "Saxe-Weimar",
    "imageLink": "img/books/faust.jpg",
    "language": "German",
    "link": "https://en.wikipedia.org/wiki/Goethe%27s_Faust",
    "pages": 158,
    "imdbId": "tt6294822",
    "title": "Faust",
    "year": 1832
  },
  {
    "author": "Nikolai Gogol",
    "country": "Russia",
    "imageLink": "img/books/dead-souls.jpg",
    "language": "Russian",
    "link": "https://en.wikipedia.org/wiki/Dead_Souls",
    "pages": 432,
    "imdbId": "tt6738046",
    "title": "Dead Souls",
    "year": 1842
  },
  {
    "author": "G\u00fcnter Grass",
    "country": "Germany",
    "imageLink": "img/books/the-tin-drum.jpg",
    "language": "German",
    "link": "https://en.wikipedia.org/wiki/The_Tin_Drum",
    "pages": 600,
    "imdbId": "tt6190198",
    "title": "The Tin Drum",
    "year": 1959
  },
  {
    "author": "Jo\u00e3o Guimar\u00e3es Rosa",
    "country": "Brazil",
    "imageLink": "img/books/the-devil-to-pay-in-the-backlands.jpg",
    "language": "Portuguese",
    "link": "https://en.wikipedia.org/wiki/The_Devil_to_Pay_in_the_Backlands",
    "pages": 494,
    "imdbId": "tt5742374",
    "title": "The Devil to Pay in the Backlands",
    "year": 1956
  },
  {
    "author": "Knut Hamsun",
    "country": "Norway",
    "imageLink": "img/books/hunger.jpg",
    "language": "Norwegian",
    "link": "https://en.wikipedia.org/wiki/Hunger_(Hamsun_novel)",
    "pages": 176,
    "imdbId": "tt3496892",
    "title": "Hunger",
    "year": 1890
  },
  {
    "author": "Ernest Hemingway",
    "country": "United States",
    "imageLink": "img/books/the-old-man-and-the-sea.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/The_Old_Man_and_the_Sea",
    "pages": 128,
    "imdbId": "tt6874964",
    "title": "The Old Man and the Sea",
    "year": 1952
  },
  {
    "author": "Homer",
    "country": "Greece",
    "imageLink": "img/books/the-iliad-of-homer.jpg",
    "language": "Greek",
    "link": "https://en.wikipedia.org/wiki/Iliad",
    "pages": 608,
    "imdbId": "tt2989350",
    "title": "Iliad",
    "year": 735
  },
  {
    "author": "Homer",
    "country": "Greece",
    "imageLink": "img/books/the-odyssey-of-homer.jpg",
    "language": "Greek",
    "link": "https://en.wikipedia.org/wiki/Odyssey",
    "pages": 374,
    "imdbId": "tt0340012",
    "title": "Odyssey",
    "year": 800
  },
  {
    "author": "Henrik Ibsen",
    "country": "Norway",
    "imageLink": "img/books/a-Dolls-house.jpg",
    "language": "Norwegian",
    "link": "https://en.wikipedia.org/wiki/A_Doll%27s_House",
    "pages": 68,
    "imdbId": "tt2243900",
    "title": "A Doll's House",
    "year": 1879
  },
  {
    "author": "James Joyce",
    "country": "Irish Free State",
    "imageLink": "img/books/ulysses.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Ulysses_(novel)",
    "pages": 228,
    "imdbId": "tt7260048",
    "title": "Ulysses",
    "year": 1922
  },
  {
    "author": "Franz Kafka",
    "country": "Czechoslovakia",
    "imageLink": "img/books/stories-of-franz-kafka.jpg",
    "language": "German",
    "link": "https://en.wikipedia.org/wiki/Franz_Kafka_bibliography#Short_stories",
    "pages": 488,
    "imdbId": "tt5079382",
    "title": "Stories",
    "year": 1924
  },
  {
    "author": "Franz Kafka",
    "country": "Czechoslovakia",
    "imageLink": "img/books/the-trial.jpg",
    "language": "German",
    "link": "https://en.wikipedia.org/wiki/The_Trial",
    "pages": 160,
    "imdbId": "tt0368709",
    "title": "The Trial",
    "year": 1925
  },
  {
    "author": "Franz Kafka",
    "country": "Czechoslovakia",
    "imageLink": "img/books/the-castle.jpg",
    "language": "German",
    "link": "https://en.wikipedia.org/wiki/The_Castle_(novel)",
    "pages": 352,
    "imdbId": "tt0250371",
    "title": "The Castle",
    "year": 1926
  },
  {
    "author": "K\u0101lid\u0101sa",
    "country": "India",
    "imageLink": "img/books/the-recognition-of-shakuntala.jpg",
    "language": "Sanskrit",
    "link": "https://en.wikipedia.org/wiki/Abhij%C3%B1%C4%81na%C5%9B%C4%81kuntalam",
    "pages": 147,
    "imdbId": "tt2317088",
    "title": "The recognition of Shakuntala",
    "year": 150
  },
  {
    "author": "Yasunari Kawabata",
    "country": "Japan",
    "imageLink": "img/books/the-sound-of-the-mountain.jpg",
    "language": "Japanese",
    "link": "https://en.wikipedia.org/wiki/The_Sound_of_the_Mountain",
    "pages": 288,
    "imdbId": "tt1413492",
    "title": "The Sound of the Mountain",
    "year": 1954
  },
  {
    "author": "Nikos Kazantzakis",
    "country": "Greece",
    "imageLink": "img/books/zorba-the-greek.jpg",
    "language": "Greek",
    "link": "https://en.wikipedia.org/wiki/Zorba_the_Greek",
    "pages": 368,
    "imdbId": "tt1590193",
    "title": "Zorba the Greek",
    "year": 1946
  },
  {
    "author": "D. H. Lawrence",
    "country": "United Kingdom",
    "imageLink": "img/books/sons-and-lovers.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Sons_and_Lovers",
    "pages": 432,
    "imdbId": "tt6135042",
    "title": "Sons and Lovers",
    "year": 1913
  },
  {
    "author": "Halld\u00f3r Laxness",
    "country": "Iceland",
    "imageLink": "img/books/independent-people.jpg",
    "language": "Icelandic",
    "link": "https://en.wikipedia.org/wiki/Independent_People",
    "pages": 470,
    "imdbId": "tt0303361",
    "title": "Independent People",
    "year": 1934
  },
  {
    "author": "Giacomo Leopardi",
    "country": "Italy",
    "imageLink": "img/books/poems-giacomo-leopardi.jpg",
    "language": "Italian",
    "link": "",
    "pages": 184,
    "imdbId": "tt7215388",
    "title": "Poems",
    "year": 1818
  },
  {
    "author": "Doris Lessing",
    "country": "United Kingdom",
    "imageLink": "img/books/the-golden-notebook.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/The_Golden_Notebook",
    "pages": 688,
    "imdbId": "tt6522634",
    "title": "The Golden Notebook",
    "year": 1962
  },
  {
    "author": "Astrid Lindgren",
    "country": "Sweden",
    "imageLink": "img/books/pippi-longstocking.jpg",
    "language": "Swedish",
    "link": "https://en.wikipedia.org/wiki/Pippi_Longstocking",
    "pages": 160,
    "imdbId": "tt8144778",
    "title": "Pippi Longstocking",
    "year": 1945
  },
  {
    "author": "Lu Xun",
    "country": "China",
    "imageLink": "img/books/diary-of-a-madman.jpg",
    "language": "Chinese",
    "link": "https://en.wikipedia.org/wiki/A_Madman%27s_Diary",
    "pages": 389,
    "imdbId": "tt6061074",
    "title": "Diary of a Madman",
    "year": 1918
  },
  {
    "author": "Naguib Mahfouz",
    "country": "Egypt",
    "imageLink": "img/books/children-of-gebelawi.jpg",
    "language": "Arabic",
    "link": "https://en.wikipedia.org/wiki/Children_of_Gebelawi",
    "pages": 355,
    "imdbId": "tt5678110",
    "title": "Children of Gebelawi",
    "year": 1959
  },
  {
    "author": "Thomas Mann",
    "country": "Germany",
    "imageLink": "img/books/buddenbrooks.jpg",
    "language": "German",
    "link": "https://en.wikipedia.org/wiki/Buddenbrooks",
    "pages": 736,
    "imdbId": "tt5039242",
    "title": "Buddenbrooks",
    "year": 1901
  },
  {
    "author": "Thomas Mann",
    "country": "Germany",
    "imageLink": "img/books/the-magic-mountain.jpg",
    "language": "German",
    "link": "https://en.wikipedia.org/wiki/The_Magic_Mountain",
    "pages": 720,
    "imdbId": "tt5304464",
    "title": "The Magic Mountain",
    "year": 1924
  },
  {
    "author": "Herman Melville",
    "country": "United States",
    "imageLink": "img/books/moby-dick.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Moby-Dick",
    "pages": 378,
    "imdbId": "tt5294966",
    "title": "Moby Dick",
    "year": 1851
  },
  {
    "author": "Michel de Montaigne",
    "country": "France",
    "imageLink": "img/books/essais.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/Essays_(Montaigne)",
    "pages": 404,
    "imdbId": "tt6336356",
    "title": "Essays",
    "year": 1595
  },
  {
    "author": "Elsa Morante",
    "country": "Italy",
    "imageLink": "img/books/history.jpg",
    "language": "Italian",
    "link": "https://en.wikipedia.org/wiki/History_(novel)",
    "pages": 600,
    "imdbId": "tt5836316",
    "title": "History",
    "year": 1974
  },
  {
    "author": "Toni Morrison",
    "country": "United States",
    "imageLink": "img/books/beloved.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Beloved_(novel)",
    "pages": 321,
    "imdbId": "tt5859238",
    "title": "Beloved",
    "year": 1987
  },
  {
    "author": "Murasaki Shikibu",
    "country": "Japan",
    "imageLink": "img/books/the-tale-of-genji.jpg",
    "language": "Japanese",
    "link": "https://en.wikipedia.org/wiki/The_Tale_of_Genji",
    "pages": 1360,
    "imdbId": "tt5776858",
    "title": "The Tale of Genji",
    "year": 1006
  },
  {
    "author": "Robert Musil",
    "country": "Austria",
    "imageLink": "img/books/the-man-without-qualities.jpg",
    "language": "German",
    "link": "https://en.wikipedia.org/wiki/The_Man_Without_Qualities",
    "pages": 365,
    "imdbId": "tt4209788",
    "title": "The Man Without Qualities",
    "year": 1931
  },
  {
    "author": "Vladimir Nabokov",
    "country": "Russia/United States",
    "imageLink": "img/books/lolita.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Lolita",
    "pages": 317,
    "imdbId": "tt6410564",
    "title": "Lolita",
    "year": 1955
  },
  {
    "author": "George Orwell",
    "country": "United Kingdom",
    "imageLink": "img/books/nineteen-eighty-four.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Nineteen_Eighty-Four",
    "pages": 272,
    "imdbId": "tt1545985",
    "title": "Nineteen Eighty-Four",
    "year": 1949
  },
  {
    "author": "Ovid",
    "country": "Roman Empire",
    "imageLink": "img/books/the-metamorphoses-of-ovid.jpg",
    "language": "Classical Latin",
    "link": "https://en.wikipedia.org/wiki/Metamorphoses",
    "pages": 576,
    "imdbId": "tt0296042",
    "title": "Metamorphoses",
    "year": 100
  },
  {
    "author": "Fernando Pessoa",
    "country": "Portugal",
    "imageLink": "img/books/the-book-of-disquiet.jpg",
    "language": "Portuguese",
    "link": "https://en.wikipedia.org/wiki/The_Book_of_Disquiet",
    "pages": 272,
    "imdbId": "tt5757738",
    "title": "The Book of Disquiet",
    "year": 1928
  },
  {
    "author": "Edgar Allan Poe",
    "country": "United States",
    "imageLink": "img/books/tales-and-poems-of-edgar-allan-poe.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Edgar_Allan_Poe_bibliography#Tales",
    "pages": 842,
    "imdbId": "tt5751998",
    "title": "Tales",
    "year": 1950
  },
  {
    "author": "Marcel Proust",
    "country": "France",
    "imageLink": "img/books/a-la-recherche-du-temps-perdu.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/In_Search_of_Lost_Time",
    "pages": 2408,
    "imdbId": "tt1727497",
    "title": "In Search of Lost Time",
    "year": 1920
  },
  {
    "author": "Fran\u00e7ois Rabelais",
    "country": "France",
    "imageLink": "img/books/gargantua-and-pantagruel.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/Gargantua_and_Pantagruel",
    "pages": 623,
    "imdbId": "tt5797164",
    "title": "Gargantua and Pantagruel",
    "year": 1533
  },
  {
    "author": "Juan Rulfo",
    "country": "Mexico",
    "imageLink": "img/books/pedro-paramo.jpg",
    "language": "Spanish",
    "link": "https://en.wikipedia.org/wiki/Pedro_P%C3%A1ramo",
    "pages": 124,
    "imdbId": "tt5999530",
    "title": "Pedro P\u00e1ramo",
    "year": 1955
  },
  {
    "author": "Rumi",
    "country": "Sultanate of Rum",
    "imageLink": "img/books/the-masnavi.jpg",
    "language": "Persian",
    "link": "https://en.wikipedia.org/wiki/Masnavi",
    "pages": 438,
    "imdbId": "tt6903636",
    "title": "The Masnavi",
    "year": 1236
  },
  {
    "author": "Salman Rushdie",
    "country": "United Kingdom, India",
    "imageLink": "img/books/midnights-children.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Midnight%27s_Children",
    "pages": 536,
    "imdbId": "tt5294550",
    "title": "Midnight's Children",
    "year": 1981
  },
  {
    "author": "Saadi",
    "country": "Persia, Persian Empire",
    "imageLink": "img/books/bostan.jpg",
    "language": "Persian",
    "link": "https://en.wikipedia.org/wiki/Bustan_(book)",
    "pages": 298,
    "imdbId": "tt6015328",
    "title": "Bostan",
    "year": 1257
  },
  {
    "author": "Tayeb Salih",
    "country": "Sudan",
    "imageLink": "img/books/season-of-migration-to-the-north.jpg",
    "language": "Arabic",
    "link": "https://en.wikipedia.org/wiki/Season_of_Migration_to_the_North",
    "pages": 139,
    "imdbId": "tt4547194",
    "title": "Season of Migration to the North",
    "year": 1966
  },
  {
    "author": "Jos\u00e9 Saramago",
    "country": "Portugal",
    "imageLink": "img/books/blindness.jpg",
    "language": "Portuguese",
    "link": "https://en.wikipedia.org/wiki/Blindness_(novel)",
    "pages": 352,
    "imdbId": "tt5796838",
    "title": "Blindness",
    "year": 1995
  },
  {
    "author": "William Shakespeare",
    "country": "England",
    "imageLink": "img/books/hamlet.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Hamlet",
    "pages": 432,
    "imdbId": "tt5711148",
    "title": "Hamlet",
    "year": 1603
  },
  {
    "author": "William Shakespeare",
    "country": "England",
    "imageLink": "img/books/king-lear.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/King_Lear",
    "pages": 384,
    "imdbId": "tt1706598",
    "title": "King Lear",
    "year": 1608
  },
  {
    "author": "William Shakespeare",
    "country": "England",
    "imageLink": "img/books/othello.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Othello",
    "pages": 314,
    "imdbId": "tt0419491",
    "title": "Othello",
    "year": 1609
  },
  {
    "author": "Sophocles",
    "country": "Greece",
    "imageLink": "img/books/oedipus-the-king.jpg",
    "language": "Greek",
    "link": "https://en.wikipedia.org/wiki/Oedipus_the_King",
    "pages": 88,
    "imdbId": "tt3230162",
    "title": "Oedipus the King",
    "year": 430
  },
  {
    "author": "Stendhal",
    "country": "France",
    "imageLink": "img/books/le-rouge-et-le-noir.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/The_Red_and_the_Black",
    "pages": 576,
    "imdbId": "tt2009432",
    "title": "The Red and the Black",
    "year": 1830
  },
  {
    "author": "Laurence Sterne",
    "country": "England",
    "imageLink": "img/books/the-life-and-opinions-of-tristram-shandy.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/The_Life_and_Opinions_of_Tristram_Shandy,_Gentleman",
    "pages": 640,
    "imdbId": "tt2141623",
    "title": "The Life And Opinions of Tristram Shandy",
    "year": 1760
  },
  {
    "author": "Italo Svevo",
    "country": "Italy",
    "imageLink": "img/books/confessions-of-zeno.jpg",
    "language": "Italian",
    "link": "https://en.wikipedia.org/wiki/Zeno%27s_Conscience",
    "pages": 412,
    "imdbId": "tt1485796",
    "title": "Confessions of Zeno",
    "year": 1923
  },
  {
    "author": "Jonathan Swift",
    "country": "Ireland",
    "imageLink": "img/books/gullivers-travels.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Gulliver%27s_Travels",
    "pages": 178,
    "imdbId": "tt3057572",
    "title": "Gulliver's Travels",
    "year": 1726
  },
  {
    "author": "Leo Tolstoy",
    "country": "Russia",
    "imageLink": "img/books/war-and-peace.jpg",
    "language": "Russian",
    "link": "https://en.wikipedia.org/wiki/War_and_Peace",
    "pages": 1296,
    "imdbId": "tt4130484",
    "title": "War and Peace",
    "year": 1867
  },
  {
    "author": "Leo Tolstoy",
    "country": "Russia",
    "imageLink": "img/books/anna-karenina.jpg",
    "language": "Russian",
    "link": "https://en.wikipedia.org/wiki/Anna_Karenina",
    "pages": 864,
    "imdbId": "tt3986978",
    "title": "Anna Karenina",
    "year": 1877
  },
  {
    "author": "Leo Tolstoy",
    "country": "Russia",
    "imageLink": "img/books/the-death-of-ivan-ilyich.jpg",
    "language": "Russian",
    "link": "https://en.wikipedia.org/wiki/The_Death_of_Ivan_Ilyich",
    "pages": 92,
    "imdbId": "tt4932154",
    "title": "The Death of Ivan Ilyich",
    "year": 1886
  },
  {
    "author": "Mark Twain",
    "country": "United States",
    "imageLink": "img/books/the-adventures-of-huckleberry-finn.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Adventures_of_Huckleberry_Finn",
    "pages": 224,
    "imdbId": "tt5208216",
    "title": "The Adventures of Huckleberry Finn",
    "year": 1884
  },
  {
    "author": "Valmiki",
    "country": "India",
    "imageLink": "img/books/ramayana.jpg",
    "language": "Sanskrit",
    "link": "https://en.wikipedia.org/wiki/Ramayana",
    "pages": 152,
    "imdbId": "tt3568002",
    "title": "Ramayana",
    "year": 450
  },
  {
    "author": "Virgil",
    "country": "Roman Empire",
    "imageLink": "img/books/the-aeneid.jpg",
    "language": "Classical Latin",
    "link": "https://en.wikipedia.org/wiki/Aeneid",
    "pages": 442,
    "imdbId": "tt4683668",
    "title": "The Aeneid",
    "year": 23
  },
  {
    "author": "Vyasa",
    "country": "India",
    "imageLink": "img/books/the-mahab-harata.jpg",
    "language": "Sanskrit",
    "link": "https://en.wikipedia.org/wiki/Mahabharata",
    "pages": 276,
    "imdbId": "tt7017474",
    "title": "Mahabharata",
    "year": 700
  },
  {
    "author": "Walt Whitman",
    "country": "United States",
    "imageLink": "img/books/leaves-of-grass.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Leaves_of_Grass",
    "pages": 152,
    "imdbId": "tt4591310",
    "title": "Leaves of Grass",
    "year": 1855
  },
  {
    "author": "Virginia Woolf",
    "country": "United Kingdom",
    "imageLink": "img/books/mrs-dalloway.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/Mrs_Dalloway",
    "pages": 216,
    "imdbId": "tt6548966",
    "title": "Mrs Dalloway",
    "year": 1925
  },
  {
    "author": "Virginia Woolf",
    "country": "United Kingdom",
    "imageLink": "img/books/to-the-lighthouse.jpg",
    "language": "English",
    "link": "https://en.wikipedia.org/wiki/To_the_Lighthouse",
    "pages": 209,
    "imdbId": "tt1103963",
    "title": "To the Lighthouse",
    "year": 1927
  },
  {
    "author": "Marguerite Yourcenar",
    "country": "France/Belgium",
    "imageLink": "img/books/memoirs-of-hadrian.jpg",
    "language": "French",
    "link": "https://en.wikipedia.org/wiki/Memoirs_of_Hadrian",
    "pages": 408,
    "imdbId": "tt1859650",
    "title": "Memoirs of Hadrian",
    "year": 1951
  }
]